apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: todo-app-base

namespace: todo-app

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "1.0.0"
    includeSelectors: false

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
