apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-application
type: Opaque
stringData:
  POSTGRES_USER: "POSTGRES_USER_PLACEHOLDER"
  POSTGRES_PASSWORD: "POSTGRES_PASSWORD_PLACEHOLDER"
  POSTGRES_DB: "POSTGRES_DB_PLACEHOLDER"
